version: "3.9"

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: testUser
      MONGO_INITDB_ROOT_PASSWORD: testUser
    networks:
      - dev

  payment-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - dev

networks:
  dev:
    name: dev
    driver: bridge