basePath: /
definitions:
  models.CreateUserDto:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  models.FailedOperation:
    properties:
      internalCode:
        type: string
      message:
        type: string
    type: object
  models.SucessfullOperation:
    properties:
      message:
        type: string
    type: object
  models.User:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server to manage payments
  title: Payment Simple API
  version: "1.0"
paths:
  /user:
    get:
      description: Get lists of users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.FailedOperation'
      summary: Get users
      tags:
      - user
    post:
      consumes:
      - application/json
      description: Create a user with his name
      parameters:
      - description: payload
        in: body
        name: CreateUserDto
        required: true
        schema:
          $ref: '#/definitions/models.CreateUserDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.SucessfullOperation'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.FailedOperation'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.FailedOperation'
      summary: Create User
      tags:
      - user
swagger: "2.0"
